// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mes_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260729105118_setPersonnelMaster")]
    partial class setPersonnelMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentClassID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("EquipmentRequirement");
                });

            modelBuilder.Entity("PLCParameter", b =>
                {
                    b.Property<int>("PlcParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlcParameterId"));

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tolerance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlcParameterId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("PLCParameters");
                });

            modelBuilder.Entity("PersonnelMaster", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonnelClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RfidTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("PersonnelMasters");
                });

            modelBuilder.Entity("PersonnelRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonnelClassID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("PersonnelRequirement");
                });

            modelBuilder.Entity("ProcessSegment", b =>
                {
                    b.Property<int>("ProcessSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessSegmentId"));

                    b.Property<int?>("ProductMasterId")
                        .HasColumnType("int");

                    b.Property<string>("SequenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("standardTimeMin")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("ProcessSegmentId");

                    b.HasIndex("ProductMasterId");

                    b.ToTable("ProcessSegments");
                });

            modelBuilder.Entity("ProductMaster", b =>
                {
                    b.Property<int>("ProductMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductMasterId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ProductMasterId");

                    b.ToTable("ProductMasters");
                });

            modelBuilder.Entity("SegmentBomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("SegmentBomItems");
                });

            modelBuilder.Entity("WorkCenter", b =>
                {
                    b.Property<int>("WorkCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkCenterId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkCenterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkCenterId");

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("WorkInstructionStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.Property<int?>("StepSequence")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StepId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("WorkInstructionSteps");
                });

            modelBuilder.Entity("WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("HasException")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PlannedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("WorkCenterId")
                        .HasColumnType("int");

                    b.Property<string>("WorkCenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("EquipmentRequirement", b =>
                {
                    b.HasOne("ProcessSegment", null)
                        .WithMany("EquipmentRequirements")
                        .HasForeignKey("ProcessSegmentId");
                });

            modelBuilder.Entity("PLCParameter", b =>
                {
                    b.HasOne("ProcessSegment", "ProcessSegment")
                        .WithMany("Parameters")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("PersonnelRequirement", b =>
                {
                    b.HasOne("ProcessSegment", null)
                        .WithMany("PersonnelRequirements")
                        .HasForeignKey("ProcessSegmentId");
                });

            modelBuilder.Entity("ProcessSegment", b =>
                {
                    b.HasOne("ProductMaster", "ProductMasters")
                        .WithMany("ProductSegments")
                        .HasForeignKey("ProductMasterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProductMasters");
                });

            modelBuilder.Entity("SegmentBomItem", b =>
                {
                    b.HasOne("ProcessSegment", "ProcessSegment")
                        .WithMany("MaterialRequirements")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("WorkInstructionStep", b =>
                {
                    b.HasOne("ProcessSegment", "ProcessSegment")
                        .WithMany("WorkInstructionSteps")
                        .HasForeignKey("ProcessSegmentId");

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("WorkOrder", b =>
                {
                    b.HasOne("WorkCenter", "WorkCenter")
                        .WithMany("WorkOrders")
                        .HasForeignKey("WorkCenterId");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("ProcessSegment", b =>
                {
                    b.Navigation("EquipmentRequirements");

                    b.Navigation("MaterialRequirements");

                    b.Navigation("Parameters");

                    b.Navigation("PersonnelRequirements");

                    b.Navigation("WorkInstructionSteps");
                });

            modelBuilder.Entity("ProductMaster", b =>
                {
                    b.Navigation("ProductSegments");
                });

            modelBuilder.Entity("WorkCenter", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
