// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mes_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260721152418_UpdateProductMaster3")]
    partial class UpdateProductMaster3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRequirement", b =>
                {
                    b.Property<string>("EquipmentClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentClassID");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("EquipmentRequirement");
                });

            modelBuilder.Entity("PLCParameter", b =>
                {
                    b.Property<int>("PlcParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlcParameterId"));

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Tolerance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlcParameterId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("PLCParameters");
                });

            modelBuilder.Entity("PersonnelRequirement", b =>
                {
                    b.Property<string>("PersonnelClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.HasKey("PersonnelClassID");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("PersonnelRequirement");
                });

            modelBuilder.Entity("ProcessSegment", b =>
                {
                    b.Property<int>("ProcessSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessSegmentId"));

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductMasterId")
                        .HasColumnType("int");

                    b.Property<string>("SequenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<decimal>("standardTimeMin")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("ProcessSegmentId");

                    b.HasIndex("ProductMasterId");

                    b.ToTable("ProcessSegments");
                });

            modelBuilder.Entity("ProductMaster", b =>
                {
                    b.Property<int>("ProductMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductMasterId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ProductMasterId");

                    b.ToTable("ProductMasters");
                });

            modelBuilder.Entity("SegmentBomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialDefinitionID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProcessSegmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("SegmentBomItems");
                });

            modelBuilder.Entity("EquipmentRequirement", b =>
                {
                    b.HasOne("ProcessSegment", null)
                        .WithMany("EquipmentRequirements")
                        .HasForeignKey("ProcessSegmentId");
                });

            modelBuilder.Entity("PLCParameter", b =>
                {
                    b.HasOne("ProcessSegment", "ProcessSegment")
                        .WithMany("Parameters")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("PersonnelRequirement", b =>
                {
                    b.HasOne("ProcessSegment", null)
                        .WithMany("PersonnelRequirements")
                        .HasForeignKey("ProcessSegmentId");
                });

            modelBuilder.Entity("ProcessSegment", b =>
                {
                    b.HasOne("ProductMaster", "ProductMasters")
                        .WithMany("ProductSegments")
                        .HasForeignKey("ProductMasterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProductMasters");
                });

            modelBuilder.Entity("SegmentBomItem", b =>
                {
                    b.HasOne("ProcessSegment", "ProcessSegment")
                        .WithMany("MaterialRequirements")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("ProcessSegment", b =>
                {
                    b.Navigation("EquipmentRequirements");

                    b.Navigation("MaterialRequirements");

                    b.Navigation("Parameters");

                    b.Navigation("PersonnelRequirements");
                });

            modelBuilder.Entity("ProductMaster", b =>
                {
                    b.Navigation("ProductSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
